In [2]:
import pandas as pd
from sklearn.manifold import TSNE

In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [5]:
df = pd.read_csv(url, names = ['sepal length','sepal width','petal length','petal width','target'])
df.head()

   sepal length  sepal width  petal length  petal width       target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
features = ['sepal length','sepal width','petal length','petal width']

In [7]:
caracteristicas = df.loc[:, features].values
target = df.loc[:, ["target"]].values

In [29]:
#inicialização do t-sne, definindo a quantidade de componentes que serão criadas e o número de iterações
tsne = TSNE(n_components=2, n_iter=1000, random_state=0)

In [30]:
caracteristicas_tsne = tsne.fit_transform(caracteristicas)

In [31]:
print(caracteristicas_tsne)

[[  8.871845    26.30605   ]
 [  7.890767    23.58316   ]
 [  9.160468    23.820482  ]
 [  8.771353    23.331438  ]
 [  9.260485    26.335878  ]
 [  9.148485    28.307503  ]
 [  9.569302    24.042257  ]
 [  8.5411005   25.625736  ]
 [  8.86158     22.564997  ]
 [  8.118322    24.198828  ]
 [  8.51906     27.874155  ]
 [  8.242482    24.979166  ]
 [  8.212299    23.375065  ]
 [  9.501674    22.49282   ]
 [  8.519533    29.194883  ]
 [  9.067713    29.34881   ]
 [  8.807878    28.471966  ]
 [  8.76767     26.375587  ]
 [  8.277923    28.674932  ]
 [  9.300569    27.389872  ]
 [  7.7305317   27.280075  ]
 [  9.094643    27.101057  ]
 [ 10.332742    24.271082  ]
 [  7.388216    26.01952   ]
 [  7.2270103   25.0403    ]
 [  7.4666924   24.07746   ]
 [  7.8897157   25.854734  ]
 [  8.468944    26.780733  ]
 [  8.428775    26.41832   ]
 [  8.636352    24.041275  ]
 [  8.009204    23.954865  ]
 [  7.83525     27.205738  ]
 [  9.602085    28.461027  ]
 [  9.14923     29.02145   ]
 [  8.118324    24.198828  ]
 [  9.158021    24.815285  ]
 [  7.916566    27.822384  ]
 [  8.118322    24.198828  ]
 [  9.171585    22.716238  ]
 [  8.456985    25.990005  ]
 [  9.2280445   25.899902  ]
 [  8.307603    22.019464  ]
 [  9.582829    23.112406  ]
 [  7.503735    26.30358   ]
 [  9.907649    27.647055  ]
 [  8.202694    23.33716   ]
 [  9.388513    27.466066  ]
 [  9.143747    23.5581    ]
 [  8.707212    27.60238   ]
 [  8.708486    25.234022  ]
 [ -2.5757902  -10.574011  ]
 [ -2.3507843   -8.88428   ]
 [ -3.1030245  -10.639105  ]
 [  0.54599595  -4.6253824 ]
 [ -2.7435524   -9.271114  ]
 [ -1.2518394   -6.015673  ]
 [ -3.0848792   -8.6271715 ]
 [  1.8932853   -3.8568676 ]
 [ -2.3645785   -9.571933  ]
 [  0.24221532  -4.30599   ]
 [  1.6096547   -3.7681758 ]
 [ -0.94955593  -6.734652  ]
 [  1.3252842   -6.088598  ]
 [ -2.5972645   -7.849845  ]
 [  1.304485    -5.386869  ]
 [ -2.0323904   -9.730634  ]
 [ -1.5688887   -5.900829  ]
 [  0.4272583   -6.007124  ]
 [ -3.4372795   -6.277285  ]
 [  0.81733894  -5.117041  ]
 [ -4.2161884   -7.762332  ]
 [ -0.05117614  -6.852141  ]
 [ -4.3541026   -9.066627  ]
 [ -2.256198    -7.6560597 ]
 [ -1.5618136   -8.592628  ]
 [ -1.9901431   -9.391654  ]
 [ -2.9761477  -10.213834  ]
 [ -4.0429444  -10.593194  ]
 [ -2.0350971   -7.2956653 ]
 [  1.6397378   -5.0649533 ]
 [  1.047573    -4.722602  ]
 [  1.3202246   -4.6837754 ]
 [  0.59447384  -5.7479157 ]
 [ -5.339723    -8.592567  ]
 [ -1.4836155   -5.373256  ]
 [ -3.0482976   -7.725575  ]
 [ -2.7353065  -10.038075  ]
 [ -3.1394212   -6.277903  ]
 [ -0.4124907   -5.745226  ]
 [  0.3540965   -4.861424  ]
 [ -0.59664893  -5.025627  ]
 [ -2.320704    -7.830413  ]
 [  0.4965406   -5.688826  ]
 [  1.8695568   -3.9133806 ]
 [ -0.28763184  -5.3275275 ]
 [ -0.5050708   -6.091618  ]
 [ -0.5385098   -5.9655013 ]
 [ -1.3453089   -7.7695184 ]
 [  2.0995283   -3.9220908 ]
 [ -0.11567451  -5.765896  ]
 [ -9.62017    -11.745633  ]
 [ -5.887055    -7.9344034 ]
 [ -8.594615   -13.423018  ]
 [ -6.629056   -11.37437   ]
 [ -7.9930115  -12.292548  ]
 [ -9.2802515  -14.712295  ]
 [ -1.1749009   -4.1057525 ]
 [ -8.654499   -14.396923  ]
 [ -6.967584   -12.781058  ]
 [ -9.704662   -13.446139  ]
 [ -7.4826283  -10.46981   ]
 [ -6.4129744  -10.5513115 ]
 [ -8.020398   -12.063826  ]
 [ -6.0685415   -7.5419955 ]
 [ -6.706416    -7.916128  ]
 [ -8.378037   -10.832794  ]
 [ -6.9123597  -11.412786  ]
 [ -9.997427   -14.444847  ]
 [ -9.221746   -15.123134  ]
 [ -4.8275967   -6.8433943 ]
 [ -8.802946   -12.598037  ]
 [ -5.9065957   -7.4189606 ]
 [ -9.178631   -14.92454   ]
 [ -4.9476924   -9.076208  ]
 [ -8.597643   -12.332673  ]
 [ -8.541419   -13.869835  ]
 [ -4.6193705   -8.640244  ]
 [ -4.6913958   -8.278922  ]
 [ -7.2216578  -11.797229  ]
 [ -8.081886   -13.907326  ]
 [ -8.598916   -14.314013  ]
 [ -9.986219   -14.433981  ]
 [ -7.4091754  -11.839887  ]
 [ -4.801174    -9.496273  ]
 [ -5.714901   -10.312829  ]
 [ -9.251172   -14.312897  ]
 [ -9.220372   -11.209376  ]
 [ -6.9120026  -11.281771  ]
 [ -4.4789596   -8.011221  ]
 [ -8.215448   -11.90947   ]
 [ -8.7208605  -11.934144  ]
 [ -8.247092   -11.135022  ]
 [ -5.8873925   -7.9359083 ]
 [ -8.977384   -12.708503  ]
 [ -9.202222   -12.087426  ]
 [ -8.096203   -11.128482  ]
 [ -5.510022    -9.197461  ]
 [ -7.2504907  -10.699677  ]
 [ -8.963941   -10.711052  ]
 [ -5.3721805   -8.088819  ]]

In [32]:
principal_df_tsne = pd.DataFrame(data=caracteristicas_tsne, columns=['Componentes 1','Componentes 2'])

In [33]:
# concatenar o df com o target
final_df_tsne = pd.concat([principal_df_tsne, df[['target']]], axis=1)
final_df_tsne.head()

   Componentes 1  Componentes 2       target
0       8.871845      26.306049  Iris-setosa
1       7.890767      23.583160  Iris-setosa
2       9.160468      23.820482  Iris-setosa
3       8.771353      23.331438  Iris-setosa
4       9.260485      26.335878  Iris-setosa

In [34]:
# imprime a qualidade do produto. A métrica divergencia KL representa o erro, quanto menor o valor, melhor o modelo
print(f'Kullback-Leibler divergence t-SNE: {tsne.kl_divergence_}')
#0.11943662911653519

Kullback-Leibler divergence t-SNE: 0.11943662911653519